M48
; DRILL file {KiCad 7.0.8} date Fri Nov 17 10:20:01 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-17T10:20:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X4.2185Y-3.465
X4.2185Y-5.3134
X5.1835Y-3.465
X5.1835Y-5.3134
T0
M30
